# Generated by Django 4.0.4 on 2022-05-29 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('sanpham', '0006_remove_loaisanpham_hang_hang_loaisanpham'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaydat', models.DateField(default=datetime.datetime.now)),
                ('hoten', models.CharField(max_length=100)),
                ('dienthoai', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('diachinhan', models.CharField(max_length=100)),
                ('ghichu', models.CharField(max_length=1000)),
                ('trangthai', models.BooleanField(default=False)),
                ('tongtien', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dongia', models.FloatField(default=0)),
                ('soluong', models.IntegerField(default=0)),
                ('donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donhangs.donhang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
        ),
    ]
