# Generated by Django 4.0.4 on 2022-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donhangs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdonhang',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
