# Generated by Django 4.0.4 on 2022-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donhangs', '0003_alter_donhang_diachinhan_alter_donhang_dienthoai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='email',
        ),
        migrations.AlterField(
            model_name='donhang',
            name='diachinhan',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='dienthoai',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ghichu',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='hoten',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
