# Generated by Django 4.0.4 on 2022-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donhangs', '0004_remove_donhang_email_alter_donhang_diachinhan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='diachinhan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='dienthoai',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ghichu',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='hoten',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
