# Generated by Django 4.0.4 on 2022-05-31 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('donhangs', '0005_alter_donhang_diachinhan_alter_donhang_dienthoai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
