# Generated by Django 4.0.4 on 2022-05-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hang',
            fields=[
                ('id_hang', models.IntegerField(primary_key=True, serialize=False)),
                ('tenhang', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id_loaisanpham', models.IntegerField(primary_key=True, serialize=False)),
                ('tenloaisanpham', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id_sanpham', models.IntegerField(primary_key=True, serialize=False)),
                ('dongia', models.FloatField(default=0)),
                ('soluong', models.IntegerField(default=0)),
                ('mota', models.CharField(max_length=10000)),
                ('hinhanh', models.CharField(max_length=1000)),
                ('tinhtrang', models.BooleanField(default=True)),
                ('hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.hang')),
                ('loaisanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.loaisanpham')),
            ],
        ),
    ]
