# Generated by Django 3.2.13 on 2022-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='tensanpham',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
