# Generated by Django 4.0.4 on 2022-05-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0004_hang_loaisanpham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hang',
            name='loaisanpham',
        ),
        migrations.AddField(
            model_name='loaisanpham',
            name='hang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sanpham.hang'),
        ),
    ]
