# Generated by Django 4.0.4 on 2022-05-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0005_remove_hang_loaisanpham_loaisanpham_hang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaisanpham',
            name='hang',
        ),
        migrations.AddField(
            model_name='hang',
            name='loaisanpham',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sanpham.loaisanpham'),
        ),
    ]
