# Generated by Django 4.0.4 on 2022-06-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0007_danhgia'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
