# Generated by Django 4.0.4 on 2022-06-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0008_danhgia_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgia',
            name='rating',
        ),
    ]
