# Generated by Django 4.0.4 on 2022-06-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0010_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rating',
        ),
    ]
