# Generated by Django 4.0.4 on 2022-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('hoten', models.CharField(max_length=100)),
                ('gioitinh', models.BooleanField(default=True)),
                ('diachi', models.CharField(max_length=100)),
                ('dienthoai', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('quyen', models.BooleanField(default=True)),
            ],
        ),
    ]
